# agents/writer_agent.py
# AgentOS - Writer Agent
# Responsible for composing the final report from all agent outputs

import os
from dotenv import load_dotenv
from google import genai

# Load API key from .env file
load_dotenv()

class WriterAgent:
    """
    Writer Agent - The communicator of AgentOS.
    Synthesizes all agent outputs into a clear, professional final report.
    """

    def __init__(self, registry, message_bus):
        self.name = "writer_agent"
        self.registry = registry
        self.message_bus = message_bus

        # Initialize Gemini client
        self.client = genai.Client(
            api_key=os.getenv("GOOGLE_API_KEY")
        )

        # Register this agent into the system
        self.registry.register(
            name=self.name,
            description="Synthesizes all findings into a professional report",
            capabilities=["write", "synthesize", "report"]
        )

    def run(self, research_result: str, analysis_result: str, topic: str, task_id: str):
        """
        Compose a final professional report from all agent outputs.
        research_result: output from Research Agent
        analysis_result: output from Analyst Agent
        topic: original topic being investigated
        task_id: unique task identifier for tracking
        """
        print(f"\n✍️ Writer Agent: Composing final report for '{topic}'...")

        # Craft a report writing prompt
        prompt = f"""
        You are a professional business report writer.
        Synthesize the following research and analysis about '{topic}' 
        into a clear, compelling executive report.
        
        RESEARCH FINDINGS:
        {research_result}
        
        STRATEGIC ANALYSIS:
        {analysis_result}
        
        Write a professional report with this structure:
        
        # Executive Report: {topic}
        
        ## Executive Summary
        (2-3 sentences capturing the most important points)
        
        ## Key Findings
        (Most important research insights)
        
        ## Strategic Recommendations
        (Clear action items from the analysis)
        
        ## Conclusion
        (Final takeaway and next steps)
        
        ---
        Report generated by AgentOS Multi-Agent System
        
        Make it professional, concise, and actionable.
        """

        # Call Gemini API
        response = self.client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        result = response.text

        # Store final report in message bus
        self.message_bus.store_result(
            agent_name=self.name,
            task_id=task_id,
            result=result
        )

        print(f"✅ Writer Agent: Final report complete!")
        return result