# agents/writer_agent.py
# AgentOS - Writer Agent
# Powered by Gemini 2.5 Flash — best for writing and synthesis

import os
from dotenv import load_dotenv
from google import genai

load_dotenv()


class WriterAgent:
    """
    Writer Agent - The communicator of AgentOS.
    Powered by Gemini 2.5 Flash for fluent, professional report writing.
    Synthesizes outputs from all providers into one cohesive report.
    """

    def __init__(self, registry, message_bus):
        self.name = "writer_agent"
        self.registry = registry
        self.message_bus = message_bus

        # Gemini is best for writing and synthesis
        self.client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
        self.model = "gemini-2.5-flash-lite"

        self.registry.register(
            name=self.name,
            description="Synthesizes all agent outputs into professional reports using Gemini",
            capabilities=["write", "synthesize", "report"],
            supported_models=["gemini-2.5-flash-lite"]
        )

    def run(self, research_result: str, analysis_result: str, topic: str, task_id: str):
        """Synthesize all agent outputs into a final professional report."""
        print(f"\n✍️  Writer Agent [Gemini]: Composing final report for '{topic}'...")

        prompt = f"""
        You are a professional business report writer.
        Synthesize the following research and analysis about '{topic}'
        into a clear, compelling executive report.

        RESEARCH FINDINGS (by Gemini):
        {research_result}

        STRATEGIC ANALYSIS + ADVISORY + VALIDATION (by DeepSeek + GLM + DeepSeek):
        {analysis_result}

        Write a professional report with this structure:

        # Executive Report: {topic}

        ## Executive Summary
        (2-3 sentences capturing the most important points)

        ## Key Findings
        (Most important research insights)

        ## Strategic Recommendations
        (Clear action items from the multi-provider analysis)

        ## Conclusion
        (Final takeaway and next steps)

        ---
        Report generated by AgentOS Multi-Agent System
        Powered by: Gemini (Google) + GLM (Zhipu AI) + DeepSeek (DeepSeek AI)

        Make it professional, concise, and actionable.
        """

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt
        )

        result = response.text

        self.message_bus.store_result(
            agent_name=self.name,
            task_id=task_id,
            result=result
        )

        print(f"✅ Writer Agent: Final report complete!")
        return result
